name: VitronMax CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint & format (ruff + black)
        run: |
          pip install ruff==0.3.1 black==24.3.0
          ruff check .          # ❌ fail on lint error
          black --check .
          
      - name: Type check
        run: |
          pip install mypy==1.9.0
          mypy app/ --strict
          
      - name: Test with pytest
        env:
          CI: "true"
        run: |
          pytest -q --cov=app
          
      - name: Build Docker image
        run: |
          docker build -t vitronmax:test .
          

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions@1.5
      
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
